name: ndpyramid
channels:
  - conda-forge
  - nodefaults
dependencies:
  - numpy
  - xarray
  - zarr
  - pooch
  - netcdf4
  - pytest
  - pytest-cov
  - pytest-mypy
  - rasterio
  - rioxarray
  - xesmf
  - pip
  - pip:
      - git+git://github.com/TomNicholas/datatree@1035a9aaf53e1c133c6e958260259b9cc0e4d293
