name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    name: ${{ matrix.python }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install git+git://github.com/TomNicholas/datatree
      - shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          python -m pip list
      - name: Running Tests
        shell: bash -l {0}
        run: |
          python -m pytest --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
      - uses: pre-commit/action@v2.0.3
